import { type Transify } from './types'
const defaultTransify: Transify = {
  COMMON_BACK: 'Back',
  COMMON_CANCEL: 'Cancel',
  COMMON_CONFIRM: 'Confirm',
  COMMON_CONTINUE_PURCHASE: 'Continue to buy',
  COMMON_COPY: 'Copy',
  COMMON_COPY_FAILED: 'fail to copy',
  COMMON_COPY_SUCCESS: 'copy successful',
  COMMON_EXCHANGE: 'redeem',
  COMMON_EXCHANGED: 'redeemed',
  COMMON_FREE: 'free',
  COMMON_GEM_CONFIRM: 'Spend {cost} gem to {NAME}?',
  COMMON_GEM_CONFIRM2: 'Spend {cost} gems for {num} spin(s)?',
  COMMON_HISTORY_DRAW: 'History',
  COMMON_HISTORY_NORECORDS: 'No records',
  COMMON_HISTORY_PURCHASE: 'Purchase history',
  COMMON_HISTORY_REDEEM: 'Redeem history',
  COMMON_NO: 'No',
  COMMON_PRIZEPOOL: 'Rewards pool',
  COMMON_PURCHASE: 'Purchase',
  COMMON_PURCHASED: 'Purchased',
  COMMON_QUANTITY_MAX: 'max',
  COMMON_RULE: 'Rules',
  COMMON_SKIP: 'Skip animation',
  COMMON_TIPS_ITEM: 'The rewards will be sent directly to your vault',
  COMMON_TIPS_TOKEN: 'tokens have been automatically accumulated',
  COMMON_YES: 'Yes',
  POPUP_NO_REMIND: "Don't remind me again",
  POPUP_TITLE_CONGRATULATIONS: 'Congratulations!',
  POPUP_TITLE_REDEEM: 'Congratulation!',
  POPUP_TITLE_UNIQUE: 'The unique items you own',
  UNIQUE_BUY_ALREADY_HAVE: 'You already own this item, if you purchase it again, it will be converted to FF tokens',
  UNIQUE_BUY_ALREADY_HAVE_PART:
    'You already own some of the item(s) you selected. If you purchase again, you will receive FF tokens instead',
  UNIQUE_REDEEM_ALREADY_HAVE: 'You already own this item, if you receive it again, it will be converted to FF tokens',
  TOAST_ERROR_CODE: 'Unknown error, error code {code}',
  TOAST_EVENTOVER: 'Event ended',
  TOAST_EVENT_CLOSED_AWHILE: 'The event is closed temporary',
  TOAST_EVENT_END: 'Event ended',
  TOAST_EVENT_NOTOPEN: "Event hasn't started",
  TOAST_EXCHANGE_SUCCESS: 'redeem successful',
  TOAST_GEM_NOT_ENOUGH: 'Insufficient diamonds, please top up and come back again',
  TOAST_LOGIN_FAILED: 'Login failed',
  TOAST_NETWORK_BUSY: 'Server busy, please try again later',
  TOAST_NETWORK_ERROR: 'Network connection error, please try again later',
  TOAST_OPERATE_BUSY: 'Too many requests, please try again later',
  TOAST_PAY_FAILED: 'Purchase failed',
  TOAST_PURCHASE_SUCCESS: 'purchase successful',
  TOAST_SERVER_BUSY: 'Server busy, please try again later',
  TOAST_SERVER_NOTWORK: 'Service unavailable',
  TOAST_SERVER_TIMEOUT: 'Service timeout',
  TOAST_WRONG_REGION: 'This event is not available for your region'
}

export { defaultTransify }
